apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend-app
  template:
    metadata:
      labels:
        app: todo-backend-app
    spec:
      containers:
        - name: todo-backend-app
          image: nomadxynta/todo_backend:1.0
