apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashresponse-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashresponse
  template:
    metadata:
      labels:
        app: hashresponse
    spec:
      containers:
        - name: hashresponse
          image: nomadxynta/hashresponse_app:1.0
