apiVersion: v1
kind: Service
metadata:
  name: images-svc
spec:
  type: ClusterIP
  selector:
    app: images # This is the app as declared in the deployment.
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
