apiVersion: v1
kind: Service
metadata:
  name: todo-backend-svc 
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: todo-backend-app
  ports:
    - port: 3002
      protocol: TCP
      targetPort: 3000
