apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: shared-todo-app
          persistentVolumeClaim:
            claimName: todo-app-pvc
      containers:
        - name: todo-app
          image: nomadxynta/todo_app:6.0
          volumeMounts:
            - name: shared-todo-app
              mountPath: /app/cache
          env:
            - name: IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: image_url

            - name: TODO_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: todo_backend_url
